// Mirrors App\Enums\Tenant\Role and App\Enums\Tenant\Permission. Update both
// sides together when permissions change — the test suite catches drift on
// the PHP side, but TS only enforces this union compile-time.

export type Role = 'clinic_admin' | 'doctor' | 'secretary' | 'nurse';

export type Permission =
    | 'patients.view'
    | 'patients.create'
    | 'patients.update'
    | 'patients.delete'
    | 'patients.view_medical'
    | 'appointments.view'
    | 'appointments.create'
    | 'appointments.update'
    | 'appointments.cancel'
    | 'appointments.delete'
    | 'consultations.view'
    | 'consultations.create'
    | 'consultations.update'
    | 'consultations.delete'
    | 'forms.view'
    | 'forms.manage'
    | 'forms.submit'
    | 'prescriptions.view'
    | 'prescriptions.create'
    | 'prescriptions.update'
    | 'prescriptions.delete'
    | 'diagnoses.view'
    | 'diagnoses.create'
    | 'diagnoses.update'
    | 'diagnoses.delete'
    | 'payments.view'
    | 'payments.create'
    | 'payments.refund'
    | 'files.view'
    | 'files.upload'
    | 'files.delete'
    | 'insurance.view'
    | 'insurance.manage'
    | 'staff.view'
    | 'staff.create'
    | 'staff.update'
    | 'staff.delete'
    | 'doctor.view_profile'
    | 'doctor.update_profile'
    | 'doctor.manage_hours'
    | 'clinic.view_settings'
    | 'clinic.update_settings'
    | 'clinic.update_branding'
    | 'clinic.manage_subscription'
    | 'services.manage'
    | 'reports.view'
    | 'reports.export'
    | 'audit.view';
